#include "main.c"
#include "common.c"
#include "gmodem.c"
#include "gmodem_apdu.c"
#include "gmodem_call.c"
#include "gmodem_cb.c"
#include "gmodem_cmd.c"
#include "gmodem_crsm.c"
#include "gmodem_device.c"
#include "gmodem_http.c"
#include "gmodem_oper.c"
#include "gmodem_scan.c"
#include "gmodem_sms.c"
//#include "pa-e1550.c"
#include "phoenix_reader.c"
#include "sec_packet.c"
#include "sims_cfg.c"
#include "sms_codec.c"


